---
title: "PRoject"
output:
  word_document: default
  html_document: default
  pdf_document: default
subtitle: 
author: sophie and Diya
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(car)
library(leaps)
myResPlots <- function(model, label){
  
  #Normal quantile plot of studentized residuals
  qqPlot(rstudent(model), pch = 19, main = paste("NQ Plot of Studentized Residuals,", label))
  
  #plot of fitted vs. studentized residuals
  plot(rstudent(model) ~ model$fitted.values, pch = 19, col = 'red', xlab = "Fitted Values", ylab = "Studentized Residuals",
     main = paste("Fits vs. Studentized Residuals,", label))
  abline(h = 0, lwd = 3)
  abline(h = c(2,-2), lty = 2, lwd = 2, col="blue")
  abline(h = c(3,-3), lty = 2, lwd = 2, col="green")

}
```

This assignment uses data from the Anime Recommendation Database 2020 on Kaggle, based on stats on myanimelist.

```{r}
anime <- read.csv("https://github.com/diyamagnetism/Stats230/raw/refs/heads/main/anime.csv")
dim(anime)
names(anime)
head(anime)



```

```{r}

library(tidyr)

anime[anime == "Unknown"] <- NA

anime$Genres <- gsub("Hentai|Ecchi|Harem", "Explicit", anime$Genres)
anime$Genres <- gsub("Yuri|Yaoi|Shounen Ai|Shoujo Ai", "LGBT", anime$Genres)
anime$Genres <- gsub("Dementia", "Psychological", anime$Genres)
anime$Genres <- gsub("Demons|Magic|Supernatural|Super Power|Vampire", "Fantasy", anime$Genres)
anime$Genres <- gsub("Space|Mecha", "Sci-Fi", anime$Genres)
anime$Genres <- gsub("Military|Cars|Police|Martial Arts", "Action", anime$Genres)
anime$Genres <- gsub("Samurai", "Historical", anime$Genres)
anime$Genres <- gsub("Parody", "Comedy", anime$Genres)


anime2 <- anime[, c("Name", "Score", "Type", "Episodes", "Aired", "Studios", "Source", "Duration", "Rating", "Popularity", "Members", "Favorites", "Dropped", "Plan.to.Watch", "Score.10", "Score.9", "Score.8", "Score.7", "Score.6", "Score.5", "Score.4", "Score.3", "Score.2", "Score.1")]

#anime2 <- separate_longer_delim(anime2, Genres, delim=",")

genres_split <- strsplit(anime$Genres, ",\\s*")
table(unlist(genres_split))
unique_genres <- sort(unique(unlist(genres_split)))


for (genre in unique_genres){
  anime2[[genre]] <- sapply(genres_split, function(x) as.integer(genre %in% x))
}

head(anime2)


```




```{r}
anime2 <- anime2[!is.na(anime2$Score), ]

anime2[is.na(anime2$Episodes),]
anime2[is.na(anime2$Episodes)&anime2$Popularity<5000, ][order(anime2$Popularity[is.na(anime2$Episodes)&anime2$Popularity<5000]), ]

anime2[anime2$Name == "One Piece",]$Episodes <- 923

anime2[anime2$Name == "Sazae-san",]$Episodes <- 2771

anime2[anime2$Name == "Boruto: Naruto Next Generations",]$Episodes <- 145

anime2[anime2$Name == "Detective Conan",]$Episodes <- 970

anime2[anime2$Name == "Beastars 2nd Season",]$Episodes <- 12

anime2[anime2$Name == "Crayon Shin-chan",]$Episodes <- 1026

anime2[anime2$Name == "Super Dragon Ball Heroes",]$Episodes <- 20

anime2[anime2$Name == "Holo no Graffiti",]$Episodes <- 42
  
anime2[anime2$Name == "Fate/Grand Order",]$Episodes <- 20

anime2[anime2$Name == "Doraemon (2005)",]$Episodes <- 591

anime2[anime2$Name == "Nintama Rantarou",]$Episodes <- 2169

anime2[anime2$Name == "Ojarumaru",]$Episodes <- 2082

anime2[anime2$Name == "Sore Ike! Anpanman",]$Episodes <- 1587
  
anime2[anime2$Name == "Chibi Maruko-chan (1995)",]$Episodes <- 1468



```

```{r}
#anime2$Duration clean this

sum(is.na(anime2$Duration))

hours <- as.numeric(gsub("?([0-9]) hr..*", "\\1", anime2$Duration))
hours[is.na(hours)]<-0
minutes<-gsub(".*?([0-9]{2}) min..*", "\\1", anime2$Duration)
minutes<-gsub(".*?([0-9]{1}) min..*", "\\1", minutes)
minutes<-as.numeric(minutes)
minutes[is.na(minutes)]<-0

anime2$TotalRuntime <- (60*hours + minutes)*(as.numeric(anime2$Episodes))


```

```{r}

anime2$Year = sum(is.na(as.integer(gsub(".* ([0-9]{4}).*", "\\1", anime2$Aired))))
anime2$Decade = floor(as.integer(gsub(".* ([0-9]{4}).*", "\\1", anime2$Aired))/10)*10



anime2$Rating <- gsub("?(.*) -.*", "\\1", anime2$Rating)
table(anime2$Rating)

table(anime2$Source)

anime2$Rating <- gsub("?(.*) -.*", "\\1", anime2$Rating)
#table(anime2$Source) clean this

names(anime2)

```

